# shared configuration between envs(dev/prod)
version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=express-mongo
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-db: