# shared configuration between envs(dev/prod)
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    image: ali0agourram/express-image
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=express-mongo
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-db: